# Generated by Django 3.1.6 on 2021-02-18 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='price',
            field=models.DecimalField(decimal_places=2, default=2.85, max_digits=10),
            preserve_default=False,
        ),
    ]
