# Generated by Django 3.1.6 on 2021-02-22 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0005_auto_20210218_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='drink',
            name='ingredients',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='drink',
            name='upload',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
